FFC-206995: date review completed including testing date
DEFRA/ffc-ahwr-farmer-claim pull request #114
Opened 2023-07-18 15:59 UTC by marcin-mogiela

2023-07-19 13:01 UTC, govTechSatish submitted a review, later dismissed

2023-07-19 13:07 UTC, liamwilson-kainos requested changes

2023-07-19 13:07 UTC, liamwilson-kainos commented on app/routes/vet-visit-date.js
> +              errorMessage: error.details.find(e => e.context.label === 'whenCarriedOut')
maybe overkill, but could maybe make the labels as string constants?

2023-07-19 14:32 UTC, marcin-mogiela commented on app/routes/vet-visit-date.js
>        }
done

2023-07-20 08:32 UTC, marcin-mogiela commented on app/views/vet-visit-date.njk
> +      {% if errors.length %}
feature toggle added

2023-07-24 07:34 UTC, chrissmKainos commented on package.json
> +  "version": "0.33.3",
This should probably be bumped up a minor version and not just patch.

2023-07-24 08:44 UTC, liamwilson-kainos submitted a review, later dismissed

2023-07-24 13:03 UTC, chrissmKainos approved these changes

2023-07-24 13:04 UTC, merged